spring.application.name=saritrack

# Supabase Connection (Transaction Mode is recommended)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.eppmobyckusswlunzxdq
spring.datasource.password=DV82rMfVgvSfr4

# Important for Supabase/Cloud DBs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Keep connections fresh for Supabase
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=200000

# Google OAuth2 Settings (Hybrid for Instructor & Render)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:959587445952-3v8re13apvpqdqrh4p6g58nplhh6n8tf.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=profile,email

server.address=0.0.0.0

# PayMongo Settings
paymongo.secret.key=${PAYMONGO_SECRET_KEY:sk_test_EuFD81y43jw329hK4HiwjWqD}
paymongo.webhook.secret=${PAYMONGO_WEBHOOK_SECRET:whsk_cNLUCkP9Qo5gHLVXemkZRCgE}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
