spring.application.name=saritrack

# Supabase Connection (Transaction Mode is recommended)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.eppmobyckusswlunzxdq
spring.datasource.password=DV82rMfVgvSfr4

# Important for Supabase/Cloud DBs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Keep connections fresh for Supabase
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=200000

# Google OAuth2 Settings
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
>>>>>>> 3e279ac (chore: add google oauth config with environment placeholders)
