spring.application.name=saritrack

# Supabase Connection (Transaction Mode is recommended)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.eppmobyckusswlunzxdq
spring.datasource.password=DV82rMfVgvSfr4

# Important for Supabase/Cloud DBs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Reduce pool size to leave room for other connections
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1